"""creacion de tablas

Revision ID: 05d378e8ffe7
Revises: 
Create Date: 2026-07-22 17:11:48.987241

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05d378e8ffe7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_black_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expira_en', sa.DateTime(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_black_list_jti'), 'token_black_list', ['jti'], unique=True)
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('rol', sa.Enum('USER', 'ADMIN', 'SUPERADMIN', name='rolusuario'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('imagen_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('permiso', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entidad', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_entidad', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('campo_cambiado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha_cambio', sa.DateTime(), nullable=False),
    sa.Column('valor_anterior', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('valor_nuevo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('accion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_id_usuario'), 'auditoria', ['id_usuario'], unique=False)
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'EN_PROGRESO', 'FINALIZADO', name='estadoticket'), nullable=False),
    sa.Column('prioridad', sa.Enum('BAJA', 'MEDIA', 'ALTA', 'CRITICA', name='prioridadticket'), nullable=False),
    sa.Column('id_usuario_creador', sa.Integer(), nullable=False),
    sa.Column('asignado', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('imagen_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario_creador'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_id_usuario_creador'), 'ticket', ['id_usuario_creador'], unique=False)
    op.create_table('comentario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ticket', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('comentario', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_ticket'], ['ticket.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comentario_id_ticket'), 'comentario', ['id_ticket'], unique=False)
    op.create_index(op.f('ix_comentario_id_usuario'), 'comentario', ['id_usuario'], unique=False)
    op.create_table('ticket_compartir',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ticket', sa.Integer(), nullable=False),
    sa.Column('id_usuario_origen', sa.Integer(), nullable=False),
    sa.Column('id_usuario_destino', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_ticket'], ['ticket.id'], ),
    sa.ForeignKeyConstraint(['id_usuario_destino'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['id_usuario_origen'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_compartir_id_ticket'), 'ticket_compartir', ['id_ticket'], unique=False)
    op.create_index(op.f('ix_ticket_compartir_id_usuario_destino'), 'ticket_compartir', ['id_usuario_destino'], unique=False)
    op.create_index(op.f('ix_ticket_compartir_id_usuario_origen'), 'ticket_compartir', ['id_usuario_origen'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_compartir_id_usuario_origen'), table_name='ticket_compartir')
    op.drop_index(op.f('ix_ticket_compartir_id_usuario_destino'), table_name='ticket_compartir')
    op.drop_index(op.f('ix_ticket_compartir_id_ticket'), table_name='ticket_compartir')
    op.drop_table('ticket_compartir')
    op.drop_index(op.f('ix_comentario_id_usuario'), table_name='comentario')
    op.drop_index(op.f('ix_comentario_id_ticket'), table_name='comentario')
    op.drop_table('comentario')
    op.drop_index(op.f('ix_ticket_id_usuario_creador'), table_name='ticket')
    op.drop_table('ticket')
    op.drop_index(op.f('ix_auditoria_id_usuario'), table_name='auditoria')
    op.drop_table('auditoria')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_token_black_list_jti'), table_name='token_black_list')
    op.drop_table('token_black_list')
    # ### end Alembic commands ###
